version: "1.0"

services:
  web:
    build: nginx
    ports:
      - 80:80
      - 443:443

    depends_on:
      - api

  api:
    build: stephensanwoweb

    environment:
      - PORT=8080

    ports:
      - 8080:8080
