name: AWS CDK Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'      
      - name: Install AWS CDK
        run : 'npm install -g aws-cdk'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        env:
            AWS_ACCOUNT: '${{ secrets.AWS_ACCOUNT }}'
            AWS_REGION: '${{ secrets.AWS_REGION }}'
            AWS_DEPLOYMENT_ENV: '${{ secrets.AWS_DEPLOYMENT_ENV }}'
            ENVIRONMENT: '${{ secrets.ENVIRONMENT }}'
        run: |
          cd web
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run AWS CDK Synth
        run: |
            cd web
            cdk synth 
  
      - name: Deploy AWS CDK
        run: |
            cd web
            cdk deploy --require-approval never
        
